version: "3.9"
services:
  app:
    build: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      COMMAND_PREFIX: ${COMMAND_PREFIX:-!}
      DB_SSL: ${DB_SSL:-true}
      DB_SSL_CA_FILE: ${DB_SSL_CA_FILE}
      PORT: ${PORT:-8080}
    ports:
      - "8080:8080"
    command: ["node","dist/index.js"]
